export const EDIT_DETAILS = 'EDIT_DETAILS';
export const CANCEL_DETAILS = 'CANCEL_DETAILS';
export const SUBMIT_DETAILS = 'SUBMIT_DETAILS';
export const UPDATE_TRIP_FIELD = 'UPDATE_TRIP_FIELD';
export const CALCULATE_FUEL_COSTS = 'CALCULATE_FUEL_COSTS';
